# Match the development interpreter and install only the web app's dependencies.
FROM python:3.14-slim

# Keep logs visible immediately and avoid generated bytecode in the image.
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1
WORKDIR /app

# Dependency installation is cached independently of application changes.
COPY requirements.txt .
RUN pip install -r requirements.txt

# Only the API and its static frontend are required at runtime.
COPY backend/ ./backend/
COPY static/ ./static/
EXPOSE 8080

# Railway provides PORT; the fallback supports local container execution.
# This configuration assumes incoming traffic uses the platform's trusted proxy.
CMD ["sh", "-c", "exec uvicorn backend.main:app --host 0.0.0.0 --port ${PORT:-8080} --proxy-headers --forwarded-allow-ips='*'"]
